# E-Commerce Orders & Transactions Analysis

## 1. Introduction

This project aims to explore and analyze an e-commerce orders and transactions dataset using Python.

The analysis will focus on understanding customer behavior, sales, products, orders, profitability, and other relevant aspects of e-commerce activity.

The project will include data exploration, data cleaning, exploratory data analysis, univariate, bivariate and multivariate visualizations, and the development of an interactive dashboard.

In [ ]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import plotly.express as px
import plotly.graph_objects as go

In [ ]:
df = pd.read_csv("../data/ecommerce_orders_transactions_2026.csv")
pd.set_option('display.max_columns', 50)

In [16]:
df.head()

,Order_ID,Order_Date,Order_Time,Customer_ID,Customer_Name,Customer_Age,Customer_Gender,Customer_Country,Customer_Continent,Customer_City,Customer_Region,Customer_Segment,Product_ID,SKU,Product_Name,Product_Category,Product_Subcategory,Brand,Quantity,Unit_Price_USD,Gross_Sales_USD,Discount_Percentage,Discount_Amount_USD,Net_Sales_USD,Tax_Rate_Percentage,Tax_USD,Shipping_Cost_USD,Total_Order_Value_USD,Payment_Method,Payment_Status,Order_Status,Shipping_Method,Delivery_Days,Return_Status,Return_Reason,Marketing_Channel,Device_Type,Coupon_Used,Coupon_Code,Customer_Rating,Review_Sentiment,Is_Repeat_Customer,Sales_Region,Warehouse,Supplier,Order_Profit_USD,Profit_Margin_Percentage,Is_Bestseller_Product,Is_New_Customer,Is_First_Order
0,ORD-105927,2026-02-10,11:34:55,CUST-000001,Mateo Park,65,Male,Canada,North America,Vancouver,British Columbia,Premium Customer,PROD-006035,HEAL-CEN-6035,Ultra Centrum Medical Devices 6035,Health & Wellness,Medical Devices,Centrum,3,45.78,137.34,20.0,27.47,109.87,10.0,10.99,59.30,180.16,Google Pay,Paid,Delivered,International,21,No Return,NaN,Organic Search,Desktop,False,NaN,3.7,Neutral,False,North America,Frankfurt,Asia Consumer Goods Ltd,-51.34,-46.73,False,False,True
1,ORD-178205,2026-02-19,10:10:49,CUST-000001,Mateo Park,65,Male,Canada,North America,Vancouver,British Columbia,Premium Customer,PROD-001611,MOBI-GOO-1611,Ultra Google Screen Protectors,Mobile Phones,Screen Protectors,Google,1,160.81,160.81,7.5,12.06,148.75,10.0,14.88,16.44,180.07,PayPal,Paid,Processing,Express,2,No Return,NaN,Email Marketing,Desktop,False,NaN,2.5,Negative,True,North America,London,International Retail Distribution,24.30,16.34,False,False,False
2,ORD-057651,2026-07-19,11:44:02,CUST-000002,Nina Wong,23,Female,New Zealand,Oceania,Auckland,Auckland,New Customer,PROD-003844,FASH-LEV-3844,Ultra Levi's Men's Clothing,Fashion,Men's Clothing,Levi's,1,278.34,278.34,10.0,27.83,250.51,15.0,37.58,9.27,297.36,Credit Card,Paid,Delivered,Standard,4,No Return,NaN,Social Media,Tablet,False,NaN,3.8,Neutral,False,Asia Pacific,Toronto,Premium Electronics Supply,64.77,25.86,False,False,True
3,ORD-124661,2026-08-26,18:13:21,CUST-000003,Aisha Moore,19,Female,Kenya,Africa,Eldoret,Mombasa,Regular Customer,PROD-003331,BOOK-HAC-3331,Pro Hachette Self-Help,Books,Self-Help,Hachette,1,86.94,86.94,15.0,13.04,73.90,16.0,11.82,8.14,93.86,Buy Now Pay Later,Paid,Delivered,Economy,8,No Return,NaN,Social Media,Tablet,False,NaN,4.9,Positive,False,Africa,Dubai,Premium Electronics Supply,9.29,12.57,False,False,True
4,ORD-162453,2026-09-08,10:34:46,CUST-000003,Aisha Moore,19,Female,Kenya,Africa,Eldoret,Mombasa,Regular Customer,PROD-006670,TOOL-MIL-6670,Luxury Milwaukee Hardware 6670,Tools & Hardware,Hardware,Milwaukee,2,73.50,147.00,25.0,36.75,110.25,16.0,17.64,22.21,150.10,Cash on Delivery,Pending,Processing,Express,3,No Return,NaN,Organic Search,Desktop,False,NaN,3.2,Neutral,True,Africa,Toronto,Global Home Supplies,-15.16,-13.75,False,False,False

In [18]:
df.shape

(200000, 50)

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 50 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Order_ID                  200000 non-null  str
 1   Order_Date                200000 non-null  str
 2   Order_Time                200000 non-null  str
 3   Customer_ID               200000 non-null  str
 4   Customer_Name             200000 non-null  str
 5   Customer_Age              200000 non-null  int64
 6   Customer_Gender           200000 non-null  str
 7   Customer_Country          200000 non-null  str
 8   Customer_Continent        200000 non-null  str
 9   Customer_City             200000 non-null  str
 10  Customer_Region           200000 non-null  str
 11  Customer_Segment          200000 non-null  str
 12  Product_ID                200000 non-null  str
 13  SKU                       200000 non-null  str
 14  Product_Name              200000 non-null  str
 15  Product_Category          200000 non-null  str
 16  Product_Subcategory       200000 non-null  str
 17  Brand                     200000 non-null  str
 18  Quantity                  200000 non-null  int64
 19  Unit_Price_USD            200000 non-null  float64
 20  Gross_Sales_USD           200000 non-null  float64
 21  Discount_Percentage       200000 non-null  float64
 22  Discount_Amount_USD       200000 non-null  float64
 23  Net_Sales_USD             200000 non-null  float64
 24  Tax_Rate_Percentage       200000 non-null  float64
 25  Tax_USD                   200000 non-null  float64
 26  Shipping_Cost_USD         200000 non-null  float64
 27  Total_Order_Value_USD     200000 non-null  float64
 28  Payment_Method            200000 non-null  str
 29  Payment_Status            200000 non-null  str
 30  Order_Status              200000 non-null  str
 31  Shipping_Method           200000 non-null  str
 32  Delivery_Days             200000 non-null  int64
 33  Return_Status             200000 non-null  str
 34  Return_Reason             8330 non-null    str
 35  Marketing_Channel         200000 non-null  str
 36  Device_Type               200000 non-null  str
 37  Coupon_Used               200000 non-null  bool
 38  Coupon_Code               29835 non-null   str
 39  Customer_Rating           200000 non-null  float64
 40  Review_Sentiment          200000 non-null  str
 41  Is_Repeat_Customer        200000 non-null  bool
 42  Sales_Region              200000 non-null  str
 43  Warehouse                 200000 non-null  str
 44  Supplier                  200000 non-null  str
 45  Order_Profit_USD          200000 non-null  float64
 46  Profit_Margin_Percentage  200000 non-null  float64
 47  Is_Bestseller_Product     200000 non-null  bool
 48  Is_New_Customer           200000 non-null  bool
 49  Is_First_Order            200000 non-null  bool
dtypes: bool(5), float64(12), int64(3), str(30)
memory usage: 127.4 MB

In [20]:
df.isnull().sum()

Order_ID                         0
Order_Date                       0
Order_Time                       0
Customer_ID                      0
Customer_Name                    0
Customer_Age                     0
Customer_Gender                  0
Customer_Country                 0
Customer_Continent               0
Customer_City                    0
Customer_Region                  0
Customer_Segment                 0
Product_ID                       0
SKU                              0
Product_Name                     0
Product_Category                 0
Product_Subcategory              0
Brand                            0
Quantity                         0
Unit_Price_USD                   0
Gross_Sales_USD                  0
Discount_Percentage              0
Discount_Amount_USD              0
Net_Sales_USD                    0
Tax_Rate_Percentage              0
Tax_USD                          0
Shipping_Cost_USD                0
Total_Order_Value_USD            0
Payment_Method                   0
Payment_Status                   0
Order_Status                     0
Shipping_Method                  0
Delivery_Days                    0
Return_Status                    0
Return_Reason               191670
Marketing_Channel                0
Device_Type                      0
Coupon_Used                      0
Coupon_Code                 170165
Customer_Rating                  0
Review_Sentiment                 0
Is_Repeat_Customer               0
Sales_Region                     0
Warehouse                        0
Supplier                         0
Order_Profit_USD                 0
Profit_Margin_Percentage         0
Is_Bestseller_Product            0
Is_New_Customer                  0
Is_First_Order                   0
dtype: int64

In [14]:
for i, columns in enumerate(df.columns, start=1):
    print(f'{i}. {columns}')

1. Order_ID
2. Order_Date
3. Order_Time
4. Customer_ID
5. Customer_Name
6. Customer_Age
7. Customer_Gender
8. Customer_Country
9. Customer_Continent
10. Customer_City
11. Customer_Region
12. Customer_Segment
13. Product_ID
14. SKU
15. Product_Name
16. Product_Category
17. Product_Subcategory
18. Brand
19. Quantity
20. Unit_Price_USD
21. Gross_Sales_USD
22. Discount_Percentage
23. Discount_Amount_USD
24. Net_Sales_USD
25. Tax_Rate_Percentage
26. Tax_USD
27. Shipping_Cost_USD
28. Total_Order_Value_USD
29. Payment_Method
30. Payment_Status
31. Order_Status
32. Shipping_Method
33. Delivery_Days
34. Return_Status
35. Return_Reason
36. Marketing_Channel
37. Device_Type
38. Coupon_Used
39. Coupon_Code
40. Customer_Rating
41. Review_Sentiment
42. Is_Repeat_Customer
43. Sales_Region
44. Warehouse
45. Supplier
46. Order_Profit_USD
47. Profit_Margin_Percentage
48. Is_Bestseller_Product
49. Is_New_Customer
50. Is_First_Order

In [15]:
df.dtypes

Order_ID                        str
Order_Date                      str
Order_Time                      str
Customer_ID                     str
Customer_Name                   str
Customer_Age                  int64
Customer_Gender                 str
Customer_Country                str
Customer_Continent              str
Customer_City                   str
Customer_Region                 str
Customer_Segment                str
Product_ID                      str
SKU                             str
Product_Name                    str
Product_Category                str
Product_Subcategory             str
Brand                           str
Quantity                      int64
Unit_Price_USD              float64
Gross_Sales_USD             float64
Discount_Percentage         float64
Discount_Amount_USD         float64
Net_Sales_USD               float64
Tax_Rate_Percentage         float64
Tax_USD                     float64
Shipping_Cost_USD           float64
Total_Order_Value_USD       float64
Payment_Method                  str
Payment_Status                  str
Order_Status                    str
Shipping_Method                 str
Delivery_Days                 int64
Return_Status                   str
Return_Reason                   str
Marketing_Channel               str
Device_Type                     str
Coupon_Used                    bool
Coupon_Code                     str
Customer_Rating             float64
Review_Sentiment                str
Is_Repeat_Customer             bool
Sales_Region                    str
Warehouse                       str
Supplier                        str
Order_Profit_USD            float64
Profit_Margin_Percentage    float64
Is_Bestseller_Product          bool
Is_New_Customer                bool
Is_First_Order                 bool
dtype: object

In [21]:
df.isnull().sum().sum()

np.int64(361835)

In [24]:
missing = df.isnull().sum()

missing = missing[missing>0].sort_values(ascending=False)

missing

Return_Reason    191670
Coupon_Code      170165
dtype: int64

In [ ]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_percentage = missing_percentage[missing_percentage > 0].sort_values(ascending=False)

missing_percentage

Return_Reason    95.8350
Coupon_Code      85.0825
dtype: float64

In [26]:
df.dtypes.value_counts()

str        30
float64    12
bool        5
int64       3
Name: count, dtype: int64

In [27]:
df["Return_Status"].value_counts(dropna=False)

Return_Status
No Return    191670
Returned       8330
Name: count, dtype: int64

In [28]:
df["Coupon_Used"].value_counts(dropna=False)

Coupon_Used
False    170165
True      29835
Name: count, dtype: int64

In [29]:
pd.crosstab(
    df["Return_Status"],
    df["Return_Reason"].isna(),
    margins=True
)

Return_Reason  False    True     All
Return_Status
No Return          0  191670  191670
Returned        8330       0    8330
All             8330  191670  200000

In [ ]:
pd.crosstab(
    df["Coupon_Used"],
    df["Coupon_Code"].isna(),
    margins=True
)

### Missing Values Analysis

The dataset contains missing values in two variables: `Return_Reason` and `Coupon_Code`.

The missing values are structurally related to other variables in the dataset. All records with `Return_Status = "No Return"` have a missing `Return_Reason`, while all returned orders have a recorded return reason.

Similarly, all records with `Coupon_Used = False` have a missing `Coupon_Code`, while orders using a coupon have a recorded coupon code.

Therefore, these missing values do not appear to represent data-entry errors. They reflect situations where the corresponding information is not applicable. The columns will therefore be retained rather than removing or statistically imputing these values.

In [ ]:
df.duplicated().sum()

In [ ]:
df["Order_ID"].duplicated().sum()

In [ ]:
df["Customer_ID"].duplicated().sum()

In [ ]:
df["Product_ID"].duplicated().sum()

### Duplicate Analysis

No exact duplicate rows were found in the dataset, and all `Order_ID` values are unique. Therefore, there is no evidence of duplicated transactions requiring removal.

Repeated `Customer_ID` and `Product_ID` values are expected because a customer can place multiple orders and a product can appear in multiple transactions. These repeated identifiers were therefore retained.

In [35]:
df["Customer_Segment"].value_counts()

Customer_Segment
Regular Customer    70528
New Customer        60267
Premium Customer    29730
At-Risk Customer    19387
VIP Customer        10191
Dormant Customer     9897
Name: count, dtype: int64

In [36]:
df["Customer_Segment"].value_counts(normalize=True) * 100

Customer_Segment
Regular Customer    35.2640
New Customer        30.1335
Premium Customer    14.8650
At-Risk Customer     9.6935
VIP Customer         5.0955
Dormant Customer     4.9485
Name: proportion, dtype: float64